return {
  'bash-language-server',
  'clangd',
  'dockerfile-language-server',
  -- 'eslint-lsp',
  'gopls',
  -- 'gradle-language-server',
  -- 'html-lsp',
  'jdtls',
  'lua-language-server',
  'marksman',
  -- 'python-lsp-server',
  'pyright',
  'texlab',
  -- 'typescript-language-server',
}
